### ISSUE TITLE
Form resolution

### ISSUE THREAD

**Issue by jamataran** [lroperod/preventive-form-app#3]
# Form resolution

## Summary

Creation of a component that allows a specific user to resolve a specific form.

## Subtasks

- [ ] (FRONT) Create a component that loads the form and its questions. It must allow the user to answer the questions.

- [ ] (BACK) Service that returns the list of questions from a form.

- [ ] (BACK) Service that allows you to save the responses of the form.

## Requirements

- The user (user role), can only fill out forms on his behalf.
